// GENERATED by packages/zap-sdk/scripts/release-cdn.mjs. Committed: the CDN
// release of `./preview` the boot loads, compiled into the npm build and the
// script-tag boot. The boot joins the path to the Zap origin it trusts (the
// framing editor, the configured Zap, or production); the SRI hash pins the
// bytes. apps/zap live-client.spec.ts checks it names a released file.

export const PREVIEW_RELEASE_PATH = '/js/preview/preview.v1.a5d4edd65a63f670.js'

export const PREVIEW_RELEASE_INTEGRITY =
  'sha384-BndA3d22q6r2xdtC8CsXM2jiTzs8BqpU2W5xNMSWbjM6wlbdx9Le3SGYxIXh+04C'
