// GENERATED by packages/zap-sdk/scripts/release-cdn.mjs. Committed: the CDN
// release of `./preview` the boot loads, compiled into the npm build and the
// script-tag boot. The boot joins the path to the Zap origin it trusts (the
// framing editor, the configured Zap, or production); the SRI hash pins the
// bytes. apps/zap live-client.spec.ts checks it names a released file.

export const PREVIEW_RELEASE_PATH = '/js/preview/preview.v1.d596b252d8afff70.js'

export const PREVIEW_RELEASE_INTEGRITY =
  'sha384-LeIaGcZk+fQNnNJs65j+955Ez72VLAP5yuHd+J0vLqdkuJX9nQi4axLNf94zCoNX'
